language: node_js
node_js:
  - 12.16.1
cache: yarn
addons:
  sonarcloud:
    organization: 'inseefr'
install:
  - yarn
before_script:
  - bash scripts/update-sonar-props.sh
  - yarn test-coverage
script:
  - sonar-scanner -Dsonar.verbose=true -X
after_script:
  - bash scripts/deploy.sh
