language: node_js
node_js:
  - 12.16.1
cache: yarn
addons:
  organization: 'inseefr'
install:
  - yarn
before_script:
  - yarn test-coverage
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - bash scripts/deploy.sh
