language: node_js
node_js:
  - 10.16.0
cache: yarn
install:
  - yarn
before_script:
  - yarn test-coverage
script:
  - cd example
  - yarn
  - yarn build

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - bash scripts/deploy.sh
