name: Lunatic CI beta

on:
  push:
    branches:
      - 'develop'

jobs:
  build-storybook-beta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: bahmutov/npm-install@v1
      - run: yarn
      # Build Storybook
      - run: yarn build-storybook
      - run: mkdir -p deploy-beta/storybook-beta
      - run: cp -R ./storybook-static/. ./deploy-beta/storybook-beta
      # Add json to fetch for suggester stories
      - run: cp -a ./public/. ./deploy-beta/storybook-beta
      - name: Upload deploy artifact
        uses: actions/upload-artifact@v3
        with:
          name: deploy-beta
          path: deploy-beta/

  deploy-storybook-beta:
    runs-on: ubuntu-latest
    needs: build-storybook-beta
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Download deploy artifact
        uses: actions/download-artifact@v3
        with:
          name: deploy-beta
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_name: 'Github action'
          message: 'Update Storybook beta (develop branch)'
          branch: 'gh-pages'


# ToDo : check if version of package.json is upgraded
  publish_beta_on_npm:
    runs-on: ubuntu-latest
    env:
      TAG: beta
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org/
      - uses: bahmutov/npm-install@v1
      - name: Get current package version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'package.json'
          prop_path: 'version'
      - run: |
          yarn build
      - name: Publishing on NPM
        run: |
          if [ "$NODE_AUTH_TOKEN" = "" ]; then
            echo "Can't publish on NPM, You must first create a secret called NPM_TOKEN that contains your NPM auth token. https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets"
            exit 1
          fi
          echo "Publish new version : ${{steps.version.outputs.prop}}-$TAG under tag: $TAG"
          yarn publish --new-version ${{steps.version.outputs.prop}}-$TAG --tag $TAG --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
