name: Lunatic CI beta

on:
  push:
    branches:
      - 'develop'

jobs:
  build-storybook-beta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: bahmutov/npm-install@v1
      - run: yarn
      # Build Storybook
      - run: yarn build-storybook
      - run: mkdir -p deploy-beta/storybook-beta
      - run: cp -R ./storybook-static/. ./deploy-beta/storybook-beta
      # Add json to fetch for suggester stories
      - run: cp -a ./public/. ./deploy-beta/storybook-beta
      - name: Upload deploy artifact
        uses: actions/upload-artifact@v3
        with:
          name: deploy-beta
          path: deploy-beta/

  check_if_version_upgraded:
    name: Check if version upgrade
    if: github.event_name == 'push' && contains('refs/heads/develop', github.ref)
    runs-on: ubuntu-latest
    needs: build-storybook-beta
    outputs:
      from_version: ${{ steps.step1.outputs.from_version }}
      to_version: ${{ steps.step1.outputs.to_version }}
      is_upgraded_version: ${{steps.step1.outputs.is_upgraded_version }}
    steps:
      - uses: garronej/github_actions_toolkit@v2.2
        id: step1
        with:
          action_name: is_package_json_version_upgraded

  deploy-beta:
    runs-on: ubuntu-latest
    needs: build-storybook-beta
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Download deploy artifact
        uses: actions/download-artifact@v3
        with:
          name: deploy-beta
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_name: 'Github action'
          message: 'Update Storybook beta (develop branch)'
          branch: 'gh-pages'
