name: OnDemand Lunatic CI (published selected branch)
on:
  workflow_dispatch:
jobs:
  publish_on_npm:
    if: github.repository == 'InseeFr/Lunatic'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Get custom version
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
            if [[ $COMMIT_MSG =~ Published:[[:space:]](.*) ]]; 
            then
              NEW_VERSION=${BASH_REMATCH[1]}
              echo "Commit message is: $COMMIT_MSG"
              echo "New version is: $NEW_VERSION"
              git config --global user.email "no-reply@insee.fr"
              git config --global user.name "Insee"
              yarn version --new-version "$NEW_VERSION"
            else
              echo "La convention du commit n'est pas respectée / Publication impossible voir le readme"
            fi
      - run: yarn build
      - name: Publishing on NPM
        run: |
          if [ "$NODE_AUTH_TOKEN" = "" ]; then
            echo "Can't publish on NPM, You must first create a secret called NPM_TOKEN that contains your NPM auth token. https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets"
            exit 1
          fi
          yarn publish --tag experimental --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}