name: Preview Lunatic CI (publish every branch)

on:
  workflow_dispatch:

jobs:

  publish_on_npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org/
      - uses: bahmutov/npm-install@v1
      - run: yarn build
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6
      - name: Generate release name with branch and date e.g preview-branche-2022-05-15T23:33:38Z
        run: echo "releasename=preview-${{ steps.branch-name.outputs.current_branch }}-${{ github.event.repository.updated_at}}" >> $GITHUB_OUTPUT
      - run: echo "Current branch ${{steps.branch-name.outputs.releasename}}"
      - name: Publishing on NPM
        run: |
          if [ "$NODE_AUTH_TOKEN" = "" ]; then
            echo "Can't publish on NPM, You must first create a secret called NPM_TOKEN that contains your NPM auth token. https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets"
            exit 1
          fi
          yarn publish --tag ${{steps.branch-name.outputs.releasename}} --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}


