name: Tests

on:
  push:
    branches:
      branches:
        - main
    pull_request_target:
      branches:
        - main

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: bahmutov/npm-install@v1
      - run: yarn
      - name: Check Typing
        run: yarn run check
      - name: Unit Tests
        run: yarn run test
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
      - name: E2E Tests
        run: yarn run test:e2e
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
